INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Front', 'Vaga Front-end', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Front', 'Vaga Front-end', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Front', 'Vaga Front-end', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Front', 'Vaga Front-end', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Front', 'Vaga Front-end', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Back', 'Vaga Back-end', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Back', 'Vaga Back-end', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Back', 'Vaga Back-end', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Back', 'Vaga Back-end', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Back', 'Vaga Back-end', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga Android', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga Android', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga Android', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga Android', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga Android', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga iOS', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga iOS', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga iOS', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga iOS', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Mobile', 'Vaga iOS', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga UX', 'Vaga UX', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga UX', 'Vaga UX', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga UX', 'Vaga UX', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga UX', 'Vaga UX', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga UX', 'Vaga UX', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Devops', 'Vaga Devops', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Devops', 'Vaga Devops', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Devops', 'Vaga Devops', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Devops', 'Vaga Devops', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga Devops', 'Vaga Devops', 5);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga GP', 'Vaga Gerente de Projetos', 1);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga GP', 'Vaga Gerente de Projetos', 2);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga GP', 'Vaga Gerente de Projetos', 3);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga GP', 'Vaga Gerente de Projetos', 4);
INSERT INTO Vaga (titulo, descricao, idEmpresa) VALUES ('Vaga GP', 'Vaga Gerente de Projetos', 5);
